### ISSUE TITLE
drawing tool brokes panning/zooming

### ISSUE THREAD

**Issue by cassiel74** [geomoose/geomoose#116]
Once I draw an element, only way to "release" the drawing tool is to select another tool (eg. zoom) then go back to pan.

Workflow:
1. choose a drawing tool
2. draw a point/line/polygon and edit or not attributes
3. panning and zooming doesn't work anymore with mouse (ie. slider zoom/pan does work)

PS I'am using Google chrome on linux

**Comment by theduckylittle** [comment]
I found the bug.

The pan tool was being disabled when the editing starts, which is the correct behaviour.  However, the pan button was not being "unchecked."  I've fixed the work flow. If you click the Pan button after editing, panning functionality will be restored.

**Comment by tchaddad** [comment]
Seems to work for me w/ build 97b9ce2.

**Comment by tchaddad** [comment]
Hmm, actually on further testing, I think Zooming is working fine after drawing, but Panning is still broken. Others should test and confirm...

**Comment by tchaddad** [comment]
OK figured ou the problem. The bug is technically fixed, however, when edit tools are enabled the mouse icon is a somewhat deceptive "hand" icon which can fool the user into thinking they have the pan tool active.

I suggest that a friendlier mouse icon for editing would be a pencil of even better, some sort of cross-hair symbol, to indicate where you are placing points / vertices.

**Comment by elil** [comment]
I think that the icon is the previous/most recent icon.  Agree that pencil or cross-hair would be a better icon for editing.

**Comment by tchaddad** [comment]
Ah, I see, so there is a logic!

Well, regardless, the problem is that the user has no indication they are still in draw mode, and they would, if we had a draw mode cursor icon...

**Comment by tchaddad** [comment]
Maybe this is now a new issue that is an enhancement?

**Comment by theduckylittle** [comment]
Closing and will address in #125
